// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SKProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("SKProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing SKProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SKProvider.Runtime"
    let [<Literal>] AssemblyProduct = "SKProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing SKProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
